### ISSUE TITLE
v0.8.1 crashing.

### ISSUE THREAD

**Issue by bjhaid** [kbst/terraform-provider-kustomization#182]
On a terraform apply with v0.8.1 provider I get:

```
Stack trace from the terraform-provider-kustomization_v0.8.1 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 1462 [running]:
github.com/kbst/terraform-provider-kustomize/kustomize.kustomizationResourceCreate(0x0?, {0x2295620?, 0xc00028e5d0})
        github.com/kbst/terraform-provider-kustomize/kustomize/resource_kustomization.go:94 +0x12b4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x27e9578?, {0x27e9578?, 0xc000d59860?}, 0xd?, {0x2295620?, 0xc00028e5d0?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0000c0b60, {0x27e9578, 0xc000d59860}, 0xc000b6ab60, 0xc0002f6a00, {0x2295620, 0xc00028e5d0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000cc78, {0x27e94d0?, 0xc000540f40?}, 0xc00061e3c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00038e500, {0x27e9578?, 0xc000514db0?}, 0xc000522000)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x24905c0?, 0xc00038e500}, {0x27e9578, 0xc000514db0}, 0xc00078be00, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002a16c0, {0x27ed730, 0xc00029f520}, 0xc000b6cfc0, 0xc0004578c0, 0x33d70e0, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0002a16c0, {0x27ed730, 0xc00029f520}, 0xc000b6cfc0, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1619 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.45.0/server.go:919 +0x28a

Error: The terraform-provider-kustomization_v0.8.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

It seems the bug was introduced in this commit: https://github.com/kbst/terraform-provider-kustomization/commit/61f16bd6f229fcb65f4db1892b56bbe7a7ac111a. Please do let me know if you need additional information to triage this bug.

Thanks

**Comment by bjhaid** [comment]
Thanks! that was really quick, I will give the new release a spin
